### ISSUE TITLE
Codes for training

### ISSUE THREAD

**Issue by shlee625** [mahmoudnafifi/SIIE#1]
Hi, Afifi.
Thanks for this awesome work. It was fun to read your paper and to test your codes.
By the way, I'm wonder that there is any plan to open your training codes too.
Thank you.

**Comment by mahmoudnafifi** [comment]
Thank you for your interest. Currently, we are not planning to release the training code. If anything changes, I will post here to get a notification.

**Comment by shlee625** [comment]
Thanks for your reply. I'll close this issue right away.

**Comment by mahmoudnafifi** [comment]
Hi @shlee625 PyTorch implementation is now available [here](https://colab.research.google.com/drive/1EtYszVLgTYv5TZFSu5_y4sCWi6UMCT8Z?usp=sharing). It includes training code.
